### PR TITLE
add ability to pass the download url as a separate option

### PR DESCRIPTION
**Pull request by iSchluff**
This commit adds the option to use a download url separate from the src. It allows using download headers for the download url.

### CODE REVIEW

**Comment by 7Ds7** [comment]
Thanks for the pull request

and sorry i only saw noticed it now, will update the plugin for version 6 and will hopefully include this.

Although i do not see the point of having a different url pointing to another than not the src video, can you tell me what was your edge case ?

**Comment by hanumantha03** [comment]
Actually this option would be really great if we are using DASH, because the src attribute of the player points to the location of .mpd and we try to download the video it gives us .mpd file.
So to download the actual .mp4 an alternate option downloadURL would be really helpful

**Comment by 7Ds7** [comment]
Sorry totally forgot this existed, merged and thank you @iSchluff

**Comment by hanumantha03** [comment]
I changed the same code in my files but it is still not working. I am pressing download but the video given to *downloadURL* is not getting downloaded

**Comment by 7Ds7** [comment]
@hanumantha03 then you are using it wrong, please check the updated readme or this pen for reference https://codepen.io/anon/pen/Lqxgvj

**Comment by hanumantha03** [comment]
I have created a new issue could you please look at the code snippet I have attached with issue.

**Pull request merged**
